---
title: "DataAnalysis_InsectData"
author: "JacquelineHoppenreijs"
date: "`r Sys.Date()`"
bibliography: references.bib
output: word_document
---
# R Markdown
Built with R version `r getRversion()`

```{r setting the scene, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(pacman)
p_load(readxl, tidyverse, plyr, dplyr, lattice, gridExtra, ggplot2, png, reshape2, colorblindcheck, lme4, emmeans, effectsize, MuMIn, performance, DHARMa, regclass, broom, vegan, patchwork, scales)

palette <- c("#104e8b", "#458b00", "#eead0e", "#9F2B68")
palette_check(palette)
palette_bivariate_plot(palette)

```

# Data description

## Vegetation data

```{r loading plant data, include = FALSE}
plant_data_2024 <- read_excel("./Data/LoL_data_JH20241008.xlsx", sheet = "LoL_veginfo_JH20240909")
plant_data_2024$Site <- as.factor(plant_data_2024$Site)
plant_data_2024$Site_type <- as.factor(plant_data_2024$Site_type)
plant_data_2024$Week <- as.factor(plant_data_2024$Week)
plant_data_2024$Species_sv <- as.factor(plant_data_2024$Species_sv)
plant_data_2024$Family_lt <- as.factor(plant_data_2024$Family_lt)
#plant_data_2024$Family_sv <- as.factor(plant_data_2024$Family_sv)
plant_data_2024$Type <- as.factor(plant_data_2024$Type)

plant_data_2024 <- plant_data_2024 %>% 
  filter(Type != "Grass" | is.na(Type))

plant_data_2024 <- plant_data_2024 %>% 
  filter(Type != "Träd" | is.na(Type))

str(plant_data_2024)

site_colors <- c("Bruksgräsmatta" = "#9F2B68", 
                   "Paradgräsmatta" = "#9F2B68", 
                   "Älvkant" = "#104e8b",        
                   "Ö_1" = "#458b00",           
                   "Ö_2" = "#458b00",           
                   "Ö_3" = "#458b00",           
                   "Ö_4" = "#458b00")           

sitetype_colors <- c("Gräsmatta" = "#9F2B68", 
                   "Älvkant" = "#104e8b",        
                   "Ö" = "#458b00")   
```

```{r build plant df}
df_plants_2024 <- ddply(plant_data_2024, ~ Week*Site_type*Site, summarise, 
                         SR = length(unique(Species_sv)))

df_plants_2024 <- df_plants_2024 %>%
  mutate(Week = as.integer(as.character(Week)))

valid_combinations <- data.frame(
  Site_type = c("Gräsmatta", "Gräsmatta", "Älvkant", "Ö", "Ö", "Ö", "Ö"),
  Site = c("Paradgräsmatta", "Bruksgräsmatta", "Älvkant", "Ö_1", "Ö_2", "Ö_3", "Ö_4"))

df_plants_2024 <- df_plants_2024 %>%
  complete(Week = 18:34, nesting(Site_type, Site), fill = list(SR = 0)) %>%
  semi_join(valid_combinations, by = c("Site_type", "Site"))

str(df_plants_2024)
```

```{r calculate total number of plant species and families in 2024, include = TRUE}
plant_SR_2024 = length(unique(plant_data_2024$Species_sv))

print(plant_SR_2024)
```

```{r plotting plant data, per week}
plot_plantSR_2024 <- ggplot(df_plants_2024, aes(x = as.factor(Week), y = SR, fill = Site)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Artrikedom (minus gräss och träd)", limits = c(0, 25), breaks = c(5, 10, 15, 20, 25)) +
  scale_fill_manual(values = site_colors, ) +
  labs(x = "Vecka", fill = "Lokal") +
  theme(legend.position = "bottom") + 
  theme_classic() +
    theme(strip.text = element_text(size = 14, face = "bold")) +
    theme(axis.title = element_text(size = 16, face = "bold")) 
plot_plantSR_2024
```

```{r build aggregated plant df}
df_plantsagg_2024 <- ddply(plant_data_2024, ~ Week*Site_type, summarise, 
                         SR = length(unique(Species_sv)))

df_plantsagg_2024 <- df_plantsagg_2024 %>%
  mutate(Week = as.integer(as.character(Week)))

df_plantsagg_2024 <- df_plantsagg_2024 %>%
  complete(Week = 18:34, nesting(Site_type), fill = list(SR = 0)) %>%
  semi_join(valid_combinations, by = c("Site_type"))

df_plantsagg_2024$Site_type <- factor(df_plantsagg_2024$Site_type, levels = c("Gräsmatta", "Älvkant", "Ö"))

str(df_plantsagg_2024)
```

```{r plotting aggregated plant data, per week}
plot_plantaggSR_2024 <- ggplot(df_plantsagg_2024, aes(x = as.factor(Week), y = SR, fill = Site_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Artrikedom (minus gräss och träd)", limits = c(0, 25), breaks = c(5, 10, 15, 20, 25)) +
  scale_fill_manual(values = sitetype_colors, ) +
  labs(x = "Vecka", fill = "Typ av lokal") +
  theme(legend.position = "bottom") + 
  theme_classic() +
    theme(strip.text = element_text(size = 14, face = "bold")) +
    theme(axis.title = element_text(size = 16, face = "bold")) 
plot_plantaggSR_2024
```

## Insect data

```{r loading insect data, include = FALSE}
insect_data_2024 <- read_excel("./Data/LoL_data_JH20241008.xlsx", sheet = "LoL_insectinfo_JH20240909")
insect_data_2024$Site <- as.factor(insect_data_2024$Site)
insect_data_2024$Site_type <- as.factor(insect_data_2024$Site_type)
insect_data_2024$Week <- as.factor(insect_data_2024$Week)
insect_data_2024$Species_sv <- as.factor(insect_data_2024$Species_sv)
insect_data_2024$Order_lt <- as.factor(insect_data_2024$Order_lt)
insect_data_2024$Order_sv <- as.factor(insect_data_2024$Order_sv)
insect_data_2024$`Pollinator?` <- as.factor(insect_data_2024$`Pollinator?`)
insect_data_2024$Behaviour <- as.factor(insect_data_2024$Behaviour)

insect_data_2024 <- insect_data_2024 %>% 
  filter(Behaviour != "Flying by" | is.na(Behaviour))

str(insect_data_2024)

site_colors <- c("Sälg" = "goldenrod",      
                   "Bruksgräsmatta" = "#9F2B68", 
                   "Paradgräsmatta" = "#9F2B68", 
                   "Älvkant" = "#104e8b",        
                   "Ö_1" = "#458b00",           
                   "Ö_2" = "#458b00",           
                   "Ö_3" = "#458b00",           
                   "Ö_4" = "#458b00")       

sitetype_colors <- c("Sälg" = "goldenrod",      
                   "Gräsmatta" = "#9F2B68", 
                   "Älvkant" = "#104e8b",        
                   "Ö" = "#458b00")    

```

```{r build insect df}
df_insects_2024 <- ddply(insect_data_2024, ~ Week*Site_type*Site, summarise, 
                         SR = length(unique(Species_sv)), 
                         Abundance = length(Species_sv))

df_insects_2024 <- df_insects_2024 %>%
  mutate(Week = as.integer(as.character(Week)))

df_insects_2024 <- df_insects_2024 %>% 
  complete(Week = 18:34, Site_type = c("Sälg", "Gräsmatta", "Älvkant", "Ö"), Site = c("Sälg", "Bruksgräsmatta", "Paradgräsmatta", "Älvkant", "Ö_1", "Ö_2", "Ö_3", "Ö_4"), fill = list(SR = 0, Abundance = 0))

df_insects_2024$Site_type <- factor(df_insects_2024$Site_type, levels = c("Sälg", "Gräsmatta", "Gräsmatta", "Älvkant", "Ö", "Ö", "Ö", "Ö"))

str(df_insects_2024)
```

```{r calculate total number of insect species and orders in 2024, include = TRUE}
insect_SR_2024 = length(unique(insect_data_2024$Species_sv))
insect_OR_2024 = length(unique(insect_data_2024$Order_lt))

print(insect_SR_2024)
print(insect_OR_2024)
```

```{r calculate total number of insects in 2024, include = TRUE}
insect_Abundance_2024 = sum(df_insects_2024$Abundance)

print(insect_Abundance_2024)
```

```{r list all insect species in 2024, include = TRUE}
list_insects_2024 = list(unique(insect_data_2024$Species_sv))

print(list_insects_2024)
```

```{r plotting insect data, per week}
plot_insectAb_2024 <- ggplot(df_insects_2024, aes(x = as.factor(Week), y = Abundance, fill = Site)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Antal insekter", limits = c(0, 50)) +
  scale_fill_manual(values = site_colors) +
  labs(x = "Vecka", fill = "Lokal") +
  theme_classic() +
    theme(strip.text = element_text(size = 14, face = "bold")) +
    theme(axis.title = element_text(size = 16, face = "bold")) 
plot_insectAb_2024

plot_insectSR_2024 <- ggplot(df_insects_2024, aes(x = as.factor(Week), y = SR, fill = Site)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Artrikedom insekter", limits = c(0, 12), breaks = c(2, 4, 6, 8, 10, 12)) +
  scale_fill_manual(values = site_colors) +
  labs(x = "Vecka", fill = "Lokal") +
  theme_classic() +
    theme(strip.text = element_text(size = 14, face = "bold")) +
    theme(axis.title = element_text(size = 16, face = "bold")) 
plot_insectSR_2024
```

```{r build aggregated insect df}
df_insectsagg_2024 <- ddply(insect_data_2024, ~ Week*Site_type, summarise, 
                         SR = length(unique(Species_sv)), 
                         Abundance = length(Species_sv))

df_insectsagg_2024 <- df_insectsagg_2024 %>%
  mutate(Week = as.integer(as.character(Week)))

df_insectsagg_2024 <- df_insectsagg_2024 %>% 
  complete(Week = 18:34, Site_type = c("Sälg", "Gräsmatta", "Älvkant", "Ö"), fill = list(SR = 0, Abundance = 0))

df_insectsagg_2024$Site_type <- factor(df_insectsagg_2024$Site_type, levels = c("Sälg", "Gräsmatta", "Älvkant", "Ö"))

str(df_insectsagg_2024)
```

```{r plotting aggregated insect data, per week}
plot_insectaggAb_2024 <- ggplot(df_insectsagg_2024, aes(x = as.factor(Week), y = Abundance, fill = Site_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Antal insekter", limits = c(0, 100)) +
  scale_fill_manual(values = sitetype_colors) +
  labs(x = "Vecka", fill = "Typ av lokal") +
  theme_classic() +
    theme(strip.text = element_text(size = 14, face = "bold")) +
    theme(axis.title = element_text(size = 16, face = "bold")) 
plot_insectaggAb_2024

plot_insectaggSR_2024 <- ggplot(df_insectsagg_2024, aes(x = as.factor(Week), y = SR, fill = Site_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Artrikedom insekter", limits = c(0, 15), breaks = c(2, 4, 6, 8, 10, 12,14)) +
  scale_fill_manual(values = sitetype_colors) +
  labs(x = "Vecka", fill = "Typ av lokal") +
  theme_classic() +
    theme(strip.text = element_text(size = 14, face = "bold")) +
    theme(axis.title = element_text(size = 16, face = "bold")) 
plot_insectaggSR_2024
```

### Pollinator subset
```{r pollinator subset}
pollinator_data_2024 <- subset(insect_data_2024, `Pollinator?` == "Yes")

df_pollinators_2024 <- ddply(pollinator_data_2024, ~ Week*Site_type*Site, summarise, 
                             SR = length(unique(Species_sv)))

df_pollinators_2024 <- df_pollinators_2024 %>%
  mutate(Week = as.integer(as.character(Week)))

df_pollinators_2024 <- df_pollinators_2024 %>% 
  complete(Week = 18:34, Site_type = c("Sälg", "Gräsmatta", "Älvkant", "Ö"), Site = c("Sälg", "Bruksgräsmatta", "Paradgräsmatta", "Älvkant", "Ö_1", "Ö_2", "Ö_3", "Ö_4"), fill = list(SR = 0))

df_pollinators_2024$Site_type <- factor(df_pollinators_2024$Site_type, levels = c("Sälg", "Gräsmatta", "Älvkant", "Ö"))

str(df_pollinators_2024)
```

```{r calculate total number of pollinator species and orders in 2024, include = TRUE}
pollinator_SR_2024 = length(unique(pollinator_data_2024$Species_sv))
pollinator_OR_2024 = length(unique(pollinator_data_2024$Order_lt))

print(pollinator_SR_2024)
print(pollinator_OR_2024)
```

```{r list all pollinator species in 2024, include = TRUE}
list_pollinators_2024 = list(unique(pollinator_data_2024$Species_sv))

print(list_pollinators_2024)
```

```{r plotting pollinator data, per week}
plot_pollinators_2024 <- ggplot(df_pollinators_2024, aes(x = as.factor(Week), y = SR, fill = Site_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Artrikedom pollinatörer", limits = c(0, 12), breaks = c(2, 4, 6, 8, 10, 12)) +
  labs(x = "Vecka", fill = NULL) +
  theme_classic()
plot_pollinators_2024

plot_pollinators_2024 <- ggplot(df_pollinators_2024, aes(x = as.factor(Week), y = SR, fill = Site_type)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_y_continuous(name = "Artrikedom pollinatörer", limits = c(0, 12), breaks = c(2, 4, 6, 8, 10, 12)) +
  labs(x = "Vecka", fill = NULL) +
  theme_classic()
plot_pollinators_2024
```

