---
title: "SPACIC manuscript"
author: "JacquelineHoppenreijs"
date: "`r Sys.Date()`"
bibliography: references.bib
output: word_document
---

```{r setting the scene, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

install.packages("pacman")
library(pacman)
p_load(readxl, tidyverse, plyr, dplyr, lattice, ggplot2, png, colorblindcheck, broom, vegan, patchwork, scales)

# Check whether the used colours are colourblindness-friendly
palette <- c("#104e8b", "#458b00", "#eead0e", "#9F2B68") 
palette_check(palette)
palette_bivariate_plot(palette)
```

```{r loading data, include = FALSE}
schooldata <- read_excel("./SPACIC/FullData_JH20241120.xlsx", sheet = "RepeatedMeasures")
schooldata$School <- as.factor(schooldata$School)
schooldata$Treatment <- as.factor(schooldata$Treatment)

str(schooldata)

control_data <- subset(schooldata, Treatment == "Control")
intervention_data <- subset(schooldata, Treatment == "Intervention")

schooldata$School_ordered = factor(schooldata$School, levels=c("NC", "ST","IC", "JM", "OZ"))
```

# Likert scale distributions
## SPACIC

```{r visualising full SPACIC, include = FALSE}
SPACIC_B_plot <- ggplot(schooldata, aes(x = Before_Full_SPACIP_mean, fill = Treatment)) +
  facet_grid( School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean SPACIC before") +
  scale_y_continuous("Number of pupils", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic() +
  theme(strip.text = element_blank()) +
  guides(fill = FALSE)  

SPACIC_A_plot <- ggplot(schooldata, aes(x = After_Full_SPACIP_mean, fill = Treatment)) +
  facet_grid( School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean SPACIC after") +
  scale_y_continuous("", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic()

SPACIC_plots <- SPACIC_B_plot + SPACIC_A_plot + plot_layout(nrow = 1)

ggsave(filename = "SPACIC_plots_20241122.png", 
       plot = SPACIC_plots, path = "SPACIC")
```

```{r full SPACIC full picture, include = TRUE}
SPACIC_plots
```

## K nowledge
```{r visualising full K, include = FALSE}
Kfull_B_plot <- ggplot(schooldata, aes(x = Before_K_mean, fill = Treatment)) +
  facet_grid( School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean K before") +
  scale_y_continuous("Number of pupils", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic() +
  theme(strip.text = element_blank()) +
  guides(fill = FALSE)  

Kfull_A_plot <- ggplot(schooldata, aes(x = After_K_mean, fill = Treatment)) +
  facet_grid( School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean K after") +
  scale_y_continuous("", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic()

Kfull_plots <- Kfull_B_plot + Kfull_A_plot + plot_layout(nrow = 1)

ggsave(filename = "Kfull_plots_20241122.png", 
       plot = Kfull_plots, path = "SPACIC")
```

```{r full K full picture, include = TRUE}
Kfull_plots
```

## C onfidence
```{r visualising full C, include = FALSE}
Cfull_B_plot <- ggplot(schooldata, aes(x = Before_C_mean, fill = Treatment)) +
  facet_grid( School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean C before") +
  scale_y_continuous("Number of pupils", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic() +
  theme(strip.text = element_blank()) +
  guides(fill = FALSE)  

Cfull_A_plot <- ggplot(schooldata, aes(x = After_C_mean, fill = Treatment)) +
  facet_grid( School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean C after") +
  scale_y_continuous("", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic()

Cfull_plots <- Cfull_B_plot + Cfull_A_plot + plot_layout(nrow = 1)

ggsave(filename = "Cfull_plots_20241122.png", 
       plot = Cfull_plots, path = "SPACIC")
```

```{r full C full picture, include = TRUE}
Cfull_plots
```

## W illingness
```{r visualising full C, include = FALSE}
Wfull_B_plot <- ggplot(schooldata, aes(x = Before_W_mean, fill = Treatment)) +
  facet_grid(School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean W before") +
  scale_y_continuous("Number of pupils", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic() +
  theme(strip.text = element_blank()) +
  guides(fill = FALSE)  

Wfull_A_plot <- ggplot(schooldata, aes(x = After_W_mean, fill = Treatment)) +
  facet_grid(School_ordered ~.) +
  geom_histogram(binwidth = 0.2) + 
  scale_x_continuous("Mean W after") +
  scale_y_continuous("", limits = c(0, 9), breaks = c(0, 2, 4, 6, 8)) +
  theme_classic()

Wfull_plots <- Wfull_B_plot + Wfull_A_plot + plot_layout(nrow = 1)

ggsave(filename = "Wfull_plots_20241122.png", 
       plot = Wfull_plots, path = "SPACIC")
```

```{r full C full picture, include = TRUE}
Wfull_plots
```

# SPACIC, K, C and W scores
## SPACIC

```{r loading more data, include = FALSE}
scoredata <- read_excel("./SPACIC/FullData_JH20241122.xlsx", sheet = "SubsetTidy")
scoredata$School <- as.factor(scoredata$School)
scoredata$Treatment <- as.factor(scoredata$Treatment)
scoredata$Timing <- as.factor(scoredata$Timing)

str(scoredata)

scoredata_b <- subset(scoredata, Timing == "Pre-Test")
scoredata_a <- subset(scoredata, Timing == "Post-Test")

control_data_b <- subset(scoredata_b, Treatment == "Control")
intervention_data_b <- subset(scoredata_b, Treatment == "Intervention")

control_data_a <- subset(scoredata_a, Treatment == "Control")
intervention_data_a <- subset(scoredata_a, Treatment == "Intervention")

scoredata$Timing_ordered = factor(scoredata$Timing, levels=c("Pre-Test", "Post-Test"))


```

```{r visualising mean SPACIC, include = FALSE}
meanSPACIC_b_Control <- mean(control_data_b$Full_SPACIP_mean)
seSPACIC_b_Control <- sd(control_data_b$Full_SPACIP_mean)/sqrt(length(control_data_b$Full_SPACIP_mean))

meanSPACIC_b_Intervention <- mean(intervention_data_b$Full_SPACIP_mean)
seSPACIC_b_Intervention <- sd(intervention_data_b$Full_SPACIP_mean)/sqrt(length(intervention_data_b$Full_SPACIP_mean))

meanSPACIC_a_Control <- mean(control_data_a$Full_SPACIP_mean)
seSPACIC_a_Control <- sd(control_data_a$Full_SPACIP_mean)/sqrt(length(control_data_a$Full_SPACIP_mean))

meanSPACIC_a_Intervention <- mean(intervention_data_a$Full_SPACIP_mean)
seSPACIC_a_Intervention <- sd(intervention_data_a$Full_SPACIP_mean)/sqrt(length(intervention_data_a$Full_SPACIP_mean))

SPACIC_data <- data.frame(
  Group = rep(c("Control", "Intervention"), each = 2),
  Moment = rep(c("Pre-Test", "Post-Test"), times = 2),
  Mean = c(meanSPACIC_b_Control, meanSPACIC_a_Control, 
           meanSPACIC_b_Intervention, meanSPACIC_a_Intervention),
  SE = c(seSPACIC_b_Control, seSPACIC_a_Control, 
         seSPACIC_b_Intervention, seSPACIC_a_Intervention)
)

SPACIC_data$Moment = factor(SPACIC_data$Moment, levels=c("Pre-Test", "Post-Test"))
SPACIC_data$Group <- factor(SPACIC_data$Group, levels = c("Control", "Intervention"))

SPACIC_plot <- ggplot(SPACIC_data, aes(x = Moment, y = Mean, group = Group)) +
  geom_line(aes(color = Group), linewidth = 1.2) + 
  geom_point(aes(color = Group), size = 4) + 
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE, color = Group), width = 0.2, size = 1.2) + 
  scale_color_manual(values = c("Control" = "azure4", "Intervention" = "black")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Mean SPACIC ± SE", limits = c(1, 5)) +
  theme_classic(base_size = 22) + 
  theme(axis.title = element_text(size = 24, face = "bold"), 
        axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(legend.position = c(0.05, 0.95), 
    legend.justification = c("left", "top"),
    legend.title = element_blank(), 
    legend.background = element_rect(fill = "white", color = "black", linewidth = 0.5)) 
SPACIC_plot
```

## K nowledge
```{r visualising mean K, include = FALSE}
meanKfull_b_Control <- mean(control_data_b$K_mean)
seKfull_b_Control <- sd(control_data_b$K_mean)/sqrt(length(control_data_b$K_mean))

meanKfull_b_Intervention <- mean(intervention_data_b$K_mean)
seKfull_b_Intervention <- sd(intervention_data_b$K_mean)/sqrt(length(intervention_data_b$K_mean))

meanKfull_a_Control <- mean(control_data_a$K_mean)
seKfull_a_Control <- sd(control_data_a$K_mean)/sqrt(length(control_data_a$K_mean))

meanKfull_a_Intervention <- mean(intervention_data_a$K_mean)
seKfull_a_Intervention <- sd(intervention_data_a$K_mean)/sqrt(length(intervention_data_a$K_mean))

Kfull_data <- data.frame(
  Group = rep(c("Control", "Intervention"), each = 2),
  Moment = rep(c("Pre-Test", "Post-Test"), times = 2),
  Mean = c(meanKfull_b_Control, meanKfull_a_Control, 
           meanKfull_b_Intervention, meanKfull_a_Intervention),
  SE = c(seKfull_b_Control, seKfull_a_Control, 
         seKfull_b_Intervention, seKfull_a_Intervention)
)

Kfull_data$Moment = factor(Kfull_data$Moment, levels=c("Pre-Test", "Post-Test"))
Kfull_data$Group <- factor(Kfull_data$Group, levels = c("Control", "Intervention"))

Kfull_plot <- ggplot(Kfull_data, aes(x = Moment, y = Mean, group = Group)) +
  geom_line(aes(color = Group), linewidth = 1.2) + 
  geom_point(aes(color = Group), size = 4) + 
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE, color = Group), width = 0.2, size = 1.2) + 
  scale_color_manual(values = c("Control" = "azure4", "Intervention" = "black")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Mean K ± SE", limits = c(1, 5)) +
  theme_classic(base_size = 22) + 
  theme(axis.title = element_text(size = 24, face = "bold")) +
  theme(legend.position = "none") #+
  #theme(legend.position = c(0.05, 0.95), 
    #legend.justification = c("left", "top"),
    #legend.title = element_blank(), 
    #legend.background = element_rect(fill = "white", color = "black", linewidth = 0.5)) 
Kfull_plot
```

## C onfidence
```{r visualising mean C, include = FALSE}
meanCfull_b_Control <- mean(control_data_b$C_mean)
seCfull_b_Control <- sd(control_data_b$C_mean)/sqrt(length(control_data_b$C_mean))

meanCfull_b_Intervention <- mean(intervention_data_b$C_mean)
seCfull_b_Intervention <- sd(intervention_data_b$C_mean)/sqrt(length(intervention_data_b$C_mean))

meanCfull_a_Control <- mean(control_data_a$C_mean)
seCfull_a_Control <- sd(control_data_a$C_mean)/sqrt(length(control_data_a$C_mean))

meanCfull_a_Intervention <- mean(intervention_data_a$C_mean)
seCfull_a_Intervention <- sd(intervention_data_a$C_mean)/sqrt(length(intervention_data_a$C_mean))

Cfull_data <- data.frame(
  Group = rep(c("Control", "Intervention"), each = 2),
  Moment = rep(c("Pre-Test", "Post-Test"), times = 2),
  Mean = c(meanCfull_b_Control, meanCfull_a_Control, 
           meanCfull_b_Intervention, meanCfull_a_Intervention),
  SE = c(seCfull_b_Control, seCfull_a_Control, 
         seCfull_b_Intervention, seCfull_a_Intervention)
)

Cfull_data$Moment = factor(Cfull_data$Moment, levels=c("Pre-Test", "Post-Test"))
Cfull_data$Group <- factor(Cfull_data$Group, levels = c("Control", "Intervention"))

Cfull_plot <- ggplot(Cfull_data, aes(x = Moment, y = Mean, group = Group)) +
  geom_line(aes(color = Group), linewidth = 1.2) + 
  geom_point(aes(color = Group), size = 4) + 
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE, color = Group), width = 0.2, size = 1.2) + 
  scale_color_manual(values = c("Control" = "azure4", "Intervention" = "black")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Mean C ± SE", limits = c(1, 5)) +
  theme_classic(base_size = 22) + 
  theme(axis.title = element_text(size = 24, face = "bold"), 
        axis.text.x = element_blank(), axis.ticks.x = element_blank()) +
  theme(legend.position = "none") #+
  #theme(legend.position = c(0.05, 0.95), 
    #legend.justification = c("left", "top"),
    #legend.title = element_blank(), 
    #legend.background = element_rect(fill = "white", color = "black", linewidth = 0.5)) 
Cfull_plot
```

## W illingness
```{r visualising mean W, include = FALSE}
meanWfull_b_Control <- mean(control_data_b$W_mean)
seWfull_b_Control <- sd(control_data_b$W_mean)/sqrt(length(control_data_b$W_mean))

meanWfull_b_Intervention <- mean(intervention_data_b$W_mean)
seWfull_b_Intervention <- sd(intervention_data_b$W_mean)/sqrt(length(intervention_data_b$W_mean))

meanWfull_a_Control <- mean(control_data_a$W_mean)
seWfull_a_Control <- sd(control_data_a$W_mean)/sqrt(length(control_data_a$W_mean))

meanWfull_a_Intervention <- mean(intervention_data_a$W_mean)
seWfull_a_Intervention <- sd(intervention_data_a$W_mean)/sqrt(length(intervention_data_a$W_mean))

Wfull_data <- data.frame(
  Group = rep(c("Control", "Intervention"), each = 2),
  Moment = rep(c("Pre-Test", "Post-Test"), times = 2),
  Mean = c(meanWfull_b_Control, meanWfull_a_Control, 
           meanWfull_b_Intervention, meanWfull_a_Intervention),
  SE = c(seWfull_b_Control, seWfull_a_Control, 
         seWfull_b_Intervention, seWfull_a_Intervention)
)

Wfull_data$Moment = factor(Wfull_data$Moment, levels=c("Pre-Test", "Post-Test"))
Wfull_data$Group <- factor(Wfull_data$Group, levels = c("Control", "Intervention"))

Wfull_plot <- ggplot(Wfull_data, aes(x = Moment, y = Mean, group = Group)) +
  geom_line(aes(color = Group), linewidth = 1.2) + 
  geom_point(aes(color = Group), size = 4) + 
  geom_errorbar(aes(ymin = Mean - SE, ymax = Mean + SE, color = Group), width = 0.2, size = 1.2) + 
  scale_color_manual(values = c("Control" = "azure4", "Intervention" = "black")) +
  scale_x_discrete(name = "") +
  scale_y_continuous(name = "Mean W ± SE", limits = c(1, 5)) +
  theme_classic(base_size = 22) + 
  theme(axis.title = element_text(size = 24, face = "bold")) +
  theme(legend.position = "none") #+
  #theme(legend.position = c(0.05, 0.95), 
    #legend.justification = c("left", "top"),
    #legend.title = element_blank(), 
    #legend.background = element_rect(fill = "white", color = "black", linewidth = 0.5)) 
Wfull_plot

```

```{r combine all line plots and save, include = TRUE}
Line_plots_20241123 <- SPACIC_plot + Cfull_plot + Kfull_plot + Wfull_plot + plot_layout(nrow = 2)
Line_plots_20241123

ggsave(filename = "Line_plots_20241123.png", 
       plot = Line_plots_20241123, path = "SPACIC")
```

# Descriptive stats
```{r loading descriptive data full, include = FALSE}
descr_data_full <- read_excel("./SPACIC/FullData_JH20241125.xlsx", sheet = "MergeFileTidy")
descr_data_full$Treatment <- as.factor(descr_data_full$Treatment)
descr_data_full$Timing <- as.factor(descr_data_full$Timing)

str(descr_data_full)
```

```{r build df suppl table 2a, include = FALSE}
descr_full_df <- ddply(descr_data_full, ~ Treatment*Timing, summarise, 
                       n_pupils = length(Full_SPACIP_mean), 
                       MeanSPACIC = mean(Full_SPACIP_mean), 
                       SESPACIC = sd(Full_SPACIP_mean)/sqrt(length(Full_SPACIP_mean)), 
                       MeanKfull = mean(K_mean), 
                       SEKfull = sd(K_mean)/sqrt(length(K_mean)),
                       MeanK_mean_dir = mean(K_mean_dir), 
                       SEK_mean_dir = sd(K_mean_dir)/sqrt(length(K_mean_dir)),
                       MeanK_mean_ind = mean(K_mean_ind), 
                       SEK_mean_ind = sd(K_mean_ind)/sqrt(length(K_mean_ind)), 
                       MeanCfull = mean(C_mean), 
                       SECfull = sd(C_mean)/sqrt(length(C_mean)),
                       MeanC_mean_dir = mean(C_mean_dir), 
                       SEC_mean_dir = sd(C_mean_dir)/sqrt(length(C_mean_dir)),
                       MeanC_mean_ind = mean(C_mean_ind), 
                       SEC_mean_ind = sd(C_mean_ind)/sqrt(length(C_mean_ind)), 
                       MeanWfull = mean(W_mean), 
                       SEWfull = sd(W_mean)/sqrt(length(W_mean)),
                       MeanW_mean_dir = mean(W_mean_dir), 
                       SEW_mean_dir = sd(W_mean_dir)/sqrt(length(W_mean_dir)),
                       MeanW_mean_ind = mean(W_mean_ind), 
                       SEW_mean_ind = sd(W_mean_ind)/sqrt(length(W_mean_ind)))
```

```{r loading descriptive data subset, include = FALSE}
descr_data_subs <- read_excel("./SPACIC/FullData_JH20241125.xlsx", sheet = "SubsetTidy")
descr_data_subs$Treatment <- as.factor(descr_data_subs$Treatment)
descr_data_subs$Timing <- as.factor(descr_data_subs$Timing)

str(descr_data_subs)
```

```{r build df suppl table 2b, include = FALSE}
descr_subs_df <- ddply(descr_data_subs, ~ Treatment*Timing, summarise, 
                       n_pupils = length(Full_SPACIP_mean), 
                       MeanSPACIC = mean(Full_SPACIP_mean), 
                       SESPACIC = sd(Full_SPACIP_mean)/sqrt(length(Full_SPACIP_mean)), 
                       MeanKfull = mean(K_mean), 
                       SEKfull = sd(K_mean)/sqrt(length(K_mean)),
                       MeanK_mean_dir = mean(K_mean_dir), 
                       SEK_mean_dir = sd(K_mean_dir)/sqrt(length(K_mean_dir)),
                       MeanK_mean_ind = mean(K_mean_ind), 
                       SEK_mean_ind = sd(K_mean_ind)/sqrt(length(K_mean_ind)), 
                       MeanCfull = mean(C_mean), 
                       SECfull = sd(C_mean)/sqrt(length(C_mean)),
                       MeanC_mean_dir = mean(C_mean_dir), 
                       SEC_mean_dir = sd(C_mean_dir)/sqrt(length(C_mean_dir)),
                       MeanC_mean_ind = mean(C_mean_ind), 
                       SEC_mean_ind = sd(C_mean_ind)/sqrt(length(C_mean_ind)), 
                       MeanWfull = mean(W_mean), 
                       SEWfull = sd(W_mean)/sqrt(length(W_mean)),
                       MeanW_mean_dir = mean(W_mean_dir), 
                       SEW_mean_dir = sd(W_mean_dir)/sqrt(length(W_mean_dir)),
                       MeanW_mean_ind = mean(W_mean_ind), 
                       SEW_mean_ind = sd(W_mean_ind)/sqrt(length(W_mean_ind)))
```

## Whole dataset

## RM subset